#!/usr/bin/env python3
"""Download a YouTube video and turn its video frames into replayable JPEGs.

The output filenames are timestamps in seconds, which is the format consumed
by camera::JpegDiskCamera. For example: ``0.000000.jpg`` and ``0.033333333.jpg``.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile


VIDEO_FORMAT = "best[height<=720]/best"


def find_executable(name: str, description: str) -> str:
    executable = shutil.which(name)
    if executable is None:
        raise RuntimeError(
            f"Could not find {description} ({name}) in PATH. "
            f"Install it or pass --{name.replace('-', '_')}."
        )
    return executable


def resolve_yt_dlp(explicit_path: str | None) -> list[str]:
    if explicit_path is not None:
        return [explicit_path]

    executable = shutil.which("yt-dlp")
    if executable is not None:
        return [executable]

    # Also support installations made with ``python -m pip install yt-dlp``.
    try:
        import yt_dlp  # noqa: F401
    except ImportError as exc:
        raise RuntimeError(
            "Could not find yt-dlp. Install it, or pass --yt-dlp PATH."
        ) from exc
    return [sys.executable, "-m", "yt_dlp"]


def resolve_js_runtime() -> list[str]:
    """Return yt-dlp arguments for an available JavaScript runtime."""
    for runtime in ("node", "deno"):
        executable = shutil.which(runtime)
        if executable is not None:
            return ["--js-runtimes", f"{runtime}:{executable}"]
    return []


def run(command: list[str]) -> None:
    print("+", " ".join(subprocess.list2cmdline([part]) for part in command))
    subprocess.run(command, check=True)


def run_capture(command: list[str]) -> str:
    print("+", " ".join(subprocess.list2cmdline([part]) for part in command))
    result = subprocess.run(
        command,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def download_video(url: str, destination: Path, yt_dlp: list[str]) -> Path:
    output_template = destination / "video.%(ext)s"
    command = [
        *yt_dlp,
        *resolve_js_runtime(),
        "--extractor-args",
        "youtube:player_client=mweb",
        "--no-playlist",
        "-f",
        VIDEO_FORMAT,
        "--merge-output-format",
        "mp4",
        "-o",
        os.fspath(output_template),
        url,
    ]
    run(command)

    videos = sorted(
        path
        for path in destination.glob("video.*")
        if path.is_file() and path.suffix.lower() not in {".part", ".ytdl"}
    )
    if len(videos) != 1:
        raise RuntimeError(
            f"Expected yt-dlp to create one video in {destination}, found: {videos}"
        )
    return videos[0]


def probe_video_timeline(
    video: Path, ffprobe: str
) -> tuple[float | None, int | None, list[float]]:
    """Return duration, decoded frame count, and per-frame timestamps."""
    stream_command = [
        ffprobe,
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-count_frames",
        "-show_entries",
        "stream=duration,nb_read_frames:format=duration",
        "-of",
        "json",
        os.fspath(video),
    ]
    metadata = json.loads(run_capture(stream_command))
    stream = metadata.get("streams", [{}])[0]
    format_metadata = metadata.get("format", {})

    duration_value = stream.get("duration", format_metadata.get("duration"))
    duration = float(duration_value) if duration_value not in (None, "N/A") else None
    frame_count_value = stream.get("nb_read_frames")
    frame_count = (
        int(frame_count_value)
        if frame_count_value not in (None, "N/A")
        else None
    )

    frame_command = [
        ffprobe,
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_frames",
        "-show_entries",
        "frame=best_effort_timestamp_time",
        "-of",
        "csv=p=0",
        os.fspath(video),
    ]
    timestamps: list[float] = []
    for line in run_capture(frame_command).splitlines():
        value = line.strip()
        if not value or value == "N/A":
            continue
        timestamp = float(value)
        if math.isfinite(timestamp):
            timestamps.append(timestamp)

    return duration, frame_count, timestamps


def choose_timestamps(
    duration: float | None,
    source_frame_count: int | None,
    source_timestamps: list[float],
    extracted_frame_count: int,
    fps: float | None,
) -> list[float]:
    """Create one video-relative timestamp for each extracted frame."""
    if extracted_frame_count == 0:
        raise RuntimeError("FFmpeg did not produce any JPEG frames")

    # Frames generated by the optional fps filter occur at these exact output
    # times. The source timeline is still probed above for duration and count.
    if fps is not None:
        return [index / fps for index in range(extracted_frame_count)]

    # best_effort_timestamp_time is the timestamp at which each source frame
    # appears. This is more accurate than assuming a constant frame rate and
    # also works for variable-frame-rate videos.
    if len(source_timestamps) == extracted_frame_count:
        first_timestamp = source_timestamps[0]
        return [timestamp - first_timestamp for timestamp in source_timestamps]

    # Some containers do not expose per-frame timestamps. For constant-rate
    # content, the stream duration divided by the number of decoded frames is
    # the frame interval; the final frame begins one interval before duration.
    if duration is not None and duration > 0:
        frame_count = source_frame_count or extracted_frame_count
        if frame_count > 0:
            interval = duration / frame_count
            return [index * interval for index in range(extracted_frame_count)]

    raise RuntimeError(
        "Could not determine timestamps: FFprobe returned neither a complete "
        "per-frame timeline nor usable duration/frame-count metadata"
    )


def extract_frames(
    video: Path,
    output_directory: Path,
    ffmpeg: str,
    ffprobe: str,
    fps: float | None,
    quality: int,
) -> int:
    """Extract sequential JPEGs and label them using the video timeline."""
    duration, source_frame_count, source_timestamps = probe_video_timeline(
        video, ffprobe
    )
    if duration is not None:
        print(
            f"Video duration: {duration:.6f}s; "
            f"decoded source frames: {source_frame_count or 'unknown'}"
        )

    with tempfile.TemporaryDirectory(
        prefix=".youtube-frames-", dir=output_directory
    ) as temporary_directory:
        temporary_frames = Path(temporary_directory)

        filters: list[str] = []
        if fps is not None:
            filters.append(f"fps={fps:g}")

        command = [
            ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            os.fspath(video),
            "-map",
            "0:v:0",
            "-fps_mode",
            "passthrough",
            "-q:v",
            str(quality),
        ]
        if filters:
            command.extend(["-vf", ",".join(filters)])
        command.extend([
            os.fspath(temporary_frames / "%012d.jpg"),
        ])
        run(command)

        extracted_frames = sorted(
            (
                int(frame.stem),
                frame,
            )
            for frame in temporary_frames.glob("*.jpg")
            if frame.stem.isdecimal()
        )
        timestamps = choose_timestamps(
            duration,
            source_frame_count,
            source_timestamps,
            len(extracted_frames),
            fps,
        )
        if len(timestamps) != len(extracted_frames):
            raise RuntimeError("FFmpeg did not produce any JPEG frames")

        for timestamp, (_, source) in zip(timestamps, extracted_frames):
            destination = output_directory / f"{timestamp:.9f}.jpg"
            if destination.exists():
                raise RuntimeError(
                    f"Timestamp collision while naming frames: {destination}"
                )
            source.rename(destination)

    return len(extracted_frames)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Download a YouTube video and create timestamped JPEG frames "
            "for JpegDiskCamera."
        )
    )
    parser.add_argument(
        "url",
        nargs="?",
        help="YouTube URL; omit this when using --video.",
    )
    parser.add_argument(
        "--video",
        type=Path,
        help="Use a local video instead of downloading the URL.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Empty directory where timestamped .jpg files will be written.",
    )
    parser.add_argument(
        "--yt-dlp",
        help="Path to yt-dlp; otherwise find yt-dlp in PATH or as a Python module.",
    )
    parser.add_argument(
        "--ffmpeg",
        default="ffmpeg",
        help="FFmpeg executable (default: ffmpeg).",
    )
    parser.add_argument(
        "--ffprobe",
        default="ffprobe",
        help="FFprobe executable (default: ffprobe).",
    )
    parser.add_argument(
        "--fps",
        type=float,
        help="Optional output frame rate; by default, preserve every source frame.",
    )
    parser.add_argument(
        "--quality",
        type=int,
        default=2,
        help="FFmpeg JPEG quality scale, 2 (best) through 31 (worst).",
    )
    parser.add_argument(
        "--keep-video",
        action="store_true",
        help="Keep the downloaded source video as source_video.<ext> in output-dir.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if (args.url is None) == (args.video is None):
        raise RuntimeError("Provide exactly one of a YouTube URL or --video.")
    if args.fps is not None and (not math.isfinite(args.fps) or args.fps <= 0):
        raise RuntimeError("--fps must be a finite positive number.")
    if not 2 <= args.quality <= 31:
        raise RuntimeError("--quality must be between 2 and 31.")

    output_directory = args.output_dir.resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    if any(output_directory.iterdir()):
        raise RuntimeError(f"Output directory is not empty: {output_directory}")

    ffmpeg = find_executable(args.ffmpeg, "FFmpeg")
    ffprobe = find_executable(args.ffprobe, "FFprobe")
    local_video = args.video.resolve() if args.video is not None else None
    if local_video is not None:
        if not local_video.is_file():
            raise RuntimeError(f"Video does not exist: {local_video}")
        downloaded_video = local_video
        temporary_directory = None
    else:
        yt_dlp = resolve_yt_dlp(args.yt_dlp)
        temporary_directory = tempfile.TemporaryDirectory(prefix="youtube-download-")
        downloaded_video = download_video(
            args.url, Path(temporary_directory.name), yt_dlp
        )

    try:
        frame_count = extract_frames(
            downloaded_video,
            output_directory,
            ffmpeg,
            ffprobe,
            args.fps,
            args.quality,
        )
        if args.keep_video and local_video is None:
            kept_video = output_directory / f"source_video{downloaded_video.suffix}"
            shutil.copy2(downloaded_video, kept_video)
            print(f"Kept source video at {kept_video}")
    finally:
        if temporary_directory is not None:
            temporary_directory.cleanup()

    print(f"Wrote {frame_count} timestamped JPEG frames to {output_directory}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1) from error
